name: Makefile CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 45 12 * * *

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-20.04]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          ref: master

    - name: configure
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get dist-upgrade
        sudo apt-get -y install linux-headers-generic dkms git bc
        uname -a

    - name: Compile
      run: |
        make
