name: Makefile CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-20.04, kali-linux-2024.1, linuxmint-21.3-cinnamon]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          ref: master

    - name: configure
      run: |
        uname -a
        sudo apt-get update
        sudo apt-get -y install linux-headers-generic dkms git bc
        uname -a

    - name: Compile
      run: |
        make
