name: SUSE Linux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [opensuse-leap-15.5]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          ref: master

    - name: Configure
      run: |
        sudo zypper update -y
        sudo zypper install -y kernel-default-devel dkms git bc
        uname -a

    - name: Compile
      run: |
        make
        sudo make install
