name: Debian

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04, ubuntu-20.04, opensuse-leap-15.5]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          ref: master

    - name: Configure
      run: |
        sudo apt-get update
        sudo apt-get -y install linux-headers-generic dkms git bc
        uname -a

    - name: Compile
      run: |
        make
        sudo make install
