name: Makefile CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 45 12 * * *

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-22.04]

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          ref: master

    - name: configure
      run: |
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt dist-upgrade
        sudo apt -y install linux-headers-$(uname -r) dkms git bc

    - name: Compile
      run: |
        make
