name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          ref: master

    - name: configure
      run: |
        sudo apt -y update
        sudo apt -y upgrade
        sudo apt dist-upgrade
        sudo apt -y install linux-headers-$(uname -r) dkms git bc

    - name: Compile
      run: |
        make
